model:
  type: wresnet28_10
dataset: cifar100
aug: randaugment
randaug:
  N: 1
  M: 30
cutout: 16
batch: 128
gpus: 1
augmentation_search_space: fixed_standard
epoch: 200
lr: 0.1
lr_schedule:
  type: cosine
optimizer:
  type: sgd
  nesterov: true
  decay: 0.0005
ac_func: Func_02
