model:
  type: shakeshake26_2x96d
dataset: cifar10
cutout: 16
batch: 128
epoch: 1800
lr: 0.01
aug: randaugment
augmentation_search_space: fixed_standard
randaug:
  N: 0
  M: 0
  weights:
  - 0.0
  - 1.0
lr_schedule:
  type: cosine
optimizer:
  type: sgd
  nesterov: true
  decay: 0.001
ac_func: Func_01
