model:
  type: wresnet28_10
dataset: cifar10
aug: randaugment
randaug:
  N: 3
  M: 5
cutout: 16
batch: 128
epoch: 200
lr: 0.05
lr_schedule:
  type: cosine
  warmup:
    multiplier: 2
    epoch: 5
optimizer:
  type: sgd
  nesterov: true
  decay: 0.0005
ac_func: Func_03
