model:
  type: wresnet40_2
dataset: cifar100
aug: randaugment
randaug:
  N: 0
  M: 0
  weights:
  - 0.0
  - 1.0
cutout: 16
batch: 128
gpus: 1
augmentation_search_space: wide_standard
epoch: 200
lr: 0.1
lr_schedule:
  type: cosine
optimizer:
  type: sgd
  nesterov: true
  decay: 0.0005
ac_func: Func_03
