model:
  type: wresnet28_10
dataset: svhn
aug: randaugment
augmentation_search_space: fixed_standard
randaug:
  N: 0
  M: 0
  weights:
  - 0.0
  - 1.0
cutout: 16
batch: 128
gpus: 8
epoch: 160
lr: 0.02
lr_schedule:
  type: cosine
  warmup:
    multiplier: 2
    epoch: 5
optimizer:
  type: sgd
  nesterov: true
  decay: 0.001
ac_func: ReLU
