all_workers_use_the_same_batches: true
model:
  type: shakeshake26_2x96d
dataset: cifar10
cutout: 16
aug: randaugment
augmentation_search_space: wide_standard
randaug:
  N: 0
  M: 0
  weights:
  - 0.0
  - 1.0
gpus: 8
batch: 64
epoch: 600
lr: 0.2
lr_schedule:
  type: cosine
optimizer:
  type: sgd
  nesterov: true
  decay: 0.0001
