model:
  type: shakeshake26_2x96d
dataset: cifar10
cutout: 16
batch: 64
epoch: 1800
lr: 0.01
aug: randaugment
randaug:
  N: 3
  M: 9
lr_schedule:
  type: cosine
optimizer:
  type: sgd
  nesterov: true
  decay: 0.001
