model:
  type: wresnet28_10
dataset: svhncore
aug: randaugment
augmentation_search_space: fixed_full
randaug:
  N: 0
  M: 0
  weights:
  - 0.0
  - 1.0
cutout: 16
batch: 64
gpus: 1
epoch: 200
lr: 0.005
lr_schedule:
  type: cosine
optimizer:
  type: sgd
  nesterov: true
  decay: 0.005
