model:
  type: wresnet28_10
dataset: svhncore
aug: randaugment
augmentation_search_space: fixed_standard
randaug:
  N: 3
  M: 9
cutout: 16
batch: 64
epoch: 200
lr: 0.0025
lr_schedule:
  type: cosine
  warmup:
    multiplier: 2
    epoch: 5
optimizer:
  type: sgd
  nesterov: true
  decay: 0.005
