model:
  type: wresnet28_10
dataset: svhncore
aug: randaugment
augmentation_search_space: fixed_standard
randaug:
  N: 0
  M: 0
  weights:
  - 0.0
  - 1.0
cutout: 16
batch: 64
gpus: 1
epoch: 200
lr: 0.02
lr_schedule:
  type: cosine
  warmup:
    multiplier: 2
    epoch: 5
optimizer:
  type: sgd
  nesterov: true
  decay: 0.005
